using System.Text.Json.Serialization;

namespace HyperliquidAiBot.Core.Models;

/// <summary>
/// Permitted trading actions emitted by ResearchEngine and evaluated by RiskManager.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TradeAction
{
    Hold,
    Buy,
    Sell,
    Close
}

/// <summary>
/// Structured trade proposal generated by the AI Research Engine.
/// </summary>
public record TradeDecision
{
    [JsonPropertyName("action")]
    public TradeAction Action { get; init; } = TradeAction.Hold;

    /// <summary>
    /// Model certainty score [0.0 - 1.0].
    /// </summary>
    [JsonPropertyName("confidence")]
    public decimal Confidence { get; init; }

    /// <summary>
    /// Suggested portfolio equity allocation percentage (e.g. 0.02 = 2%).
    /// </summary>
    [JsonPropertyName("allocationPct")]
    public decimal AllocationPct { get; init; }

    /// <summary>
    /// Suggested stop-loss percentage from entry price (e.g., 0.02 = 2%).
    /// </summary>
    [JsonPropertyName("suggestedStopLossPct")]
    public decimal? SuggestedStopLossPct { get; init; }

    /// <summary>
    /// Suggested take-profit percentage from entry price (e.g., 0.04 = 4%).
    /// </summary>
    [JsonPropertyName("suggestedTakeProfitPct")]
    public decimal? SuggestedTakeProfitPct { get; init; }

    /// <summary>
    /// Step-by-step quantitative reasoning behind the trade proposal.
    /// </summary>
    [JsonPropertyName("reasoning")]
    public string Reasoning { get; init; } = string.Empty;

    /// <summary>
    /// Indicators referenced in forming this hypothesis (e.g. ["RSI", "MACD_BULLISH_CROSS"]).
    /// </summary>
    [JsonPropertyName("keyIndicatorsCited")]
    public List<string> KeyIndicatorsCited { get; init; } = new();

    [JsonPropertyName("timestampUtc")]
    public DateTime TimestampUtc { get; init; } = DateTime.UtcNow;
}

/// <summary>
/// Output of deterministic safety verification performed by RiskManager.
/// </summary>
public record RiskEvaluation
{
    public bool IsApproved { get; init; }
    public string? RejectionReason { get; init; }
    public TradeAction Action { get; init; }
    public decimal OriginalConfidence { get; init; }
    public decimal ApprovedSize { get; init; }
    public decimal EntryPrice { get; init; }
    public decimal? StopLossPrice { get; init; }
    public decimal? TakeProfitPrice { get; init; }
    public decimal AppliedStopLossPct { get; init; }
    public decimal AppliedTakeProfitPct { get; init; }
    public decimal NotionalUsdValue { get; init; }
    public List<string> SafetyAuditLogs { get; init; } = new();

    public static RiskEvaluation Reject(string reason, TradeAction action, decimal confidence) =>
        new()
        {
            IsApproved = false,
            RejectionReason = reason,
            Action = action,
            OriginalConfidence = confidence,
            SafetyAuditLogs = { $"Trade REJECTED: {reason}" }
        };
}
